package main.java;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rupakhet' at '12/2/16 12:19 PM' with Gradle 3.0
 *
 * @author rupakhet, @date 12/2/16 12:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
